### PR TITLE
Webcal support

### PR DESCRIPTION
**Pull request by richardvanthof**
### Description
This PR introduces a feature allowing users to subscribe to the event calendar of NL-CL. Once subscribed, new events will automatically appear in their calendar application. This feature aims to improve user engagement by ensuring they stay updated with the latest events without manual intervention. I also added functionality to add single events to a calendar.

### Changes
- Restructured event-posts to make them generate the correct data for the ics-files.
- Set up Hugo to create ics-files alongside the regular html-pages.
- Added subscribe-buttons.
- Minor styling changes to make the new elements look somewhat correct.
- Wrote new instructions in the README for adding events.

### Motivation
Find your events interesting but I sometimes miss them since I'm too lazy to look online :).

### How to test
Open the following test-link in your browser (or use this link to subscribe in, for instance, Google Calendar): 
```webcal://bawdy-waves.surge.sh/events/calendar.ics```

### Possible improvements
- Styling.
- Hugo sometimes doesn't always apply my additions in customstyle.css.

### CODE REVIEW

**Comment by tmhglnd** [comment]
Hi! I haven't looked at it yet but I'm already excited for this feature. I think the idea is great to be able to subscribe to a calendar, definitely very useful! I'll try to make some time the coming week to look at your changes. I'm not sure we met at a meetup already, but nonetheless thanks for your engagement and pull request! Best, Timo

**Comment by richardvanthof** [comment]
Hey, glad you like it! Don't think we've met yet, usually I go to events in Rotterdam. Also, take your time reviewing and just shoot me a message if you have questions. Cheers! Richard

**Comment by tmhglnd** [comment]
Hi! I tried the test link with my mac calendar app, but it gives an error after I click subscribe. First it says: `The connection is not secure. Do you want to continue subscribing?` When I click continue it says: `There was an unexpected error with the request on subscribed calendars (error -1).`

I tried running it locally and then the subscription does work, so maybe your url expired or something else happened?

I also looked a bit at the code for the .ics list and single file. 

It seems in the `location = ` only the part before the `,` is actually included in the .ics file for the location. Is there a way to include the whole line you think? For example now: `[V2_Lab for the Unstable Media, Eendrachtsstraat 10, Rotterdam NL]()` only results in: `V2_Lab for the Unstable Media`. I guess this has something to do with how the .ics file works, maybe commas are not allowed. The `markdownify` and `plainify` don't seem to cause this because it does work if I add the location to the `description:` line. 

I've added some stuff to the ics list and single templates so all the times and the location/url to the map also end up in the description. Also the `doors=` and `price=` are optional, and if there is no doors specified it uses the `start=` as the door time also. I wasn't sure yet if the start time of the event in the calendar should be the doors-time, or the actual start time, but I guess the actual start time makes sense, and having the doors-time in the description helps to clarify.

I think the headers of the meetup markdown files become a bit messy now tho, but I've tried to restructure that a bit with tabs and linebreaks (maybe more personal preference than necessity). Not sure there is anything to do about it so i'm okay with how it is now.

One thing I also noticed is that it wasn't possible to run `hugo server -F -D`, because the `markdown-guide.md` file was an "event" but couldn't be rendered because it does not include the correct info (was an easy fix by just adding the start/end times, but still something we have to look out for in future files that are added as event posts). Finding ways to make this a bit more foolproof would be good maybe.

I haven't been able to find where it's coming from, but for some reason the homepage now has a `_` in the top left corner.

**Comment by richardvanthof** [comment]
Hey, thanks for your response. Will look into it asap.

**Comment by richardvanthof** [comment]
> I tried the test link with my mac calendar app, but it gives an error after I click subscribe. First it says: The connection is not secure. Do you want to continue subscribing? When I click continue it says: There was an unexpected error with the request on subscribed calendars (error -1).. I tried running it locally and then the subscription does work, so maybe your url expired or something else happened?
> 

Hmm, interesting. I just tested in Apple Calendar, Google Calendar, Proton Calendar and Thunderbird (multiple machines) and the webcal link does seem to work.

- If you go to https://bawdy-waves.surge.sh/events/calendar.ics in your browser: does it give you a valid ics-file at all?
- Does subscribing manually via https://bawdy-waves.surge.sh/events/calendar.ics also fail? (http is often more reliable than webcal).

I will try to [check](https://icalendar.org/validator.html?url=http://bawdy-waves.surge.sh/events/calendar.ics) if the ics-template completely adheres to the spec.

> I also looked a bit at the code for the .ics list and single [file.It](http://file.it/) seems in the location =  only the part before the , is actually included in the .ics file for the location. Is there a way to include the whole line you think? For example now: [[V2_Lab for the Unstable Media, Eendrachtsstraat 10, Rotterdam NL](https://github.com/netherlands-coding-live/netherlands-coding-live.github.io/pull/5)]() only results in: V2_Lab for the Unstable Media. I guess this has something to do with how the .ics file works, maybe commas are not allowed. The markdownify and plainify don't seem to cause this because it does work if I add the location to the description: line.
> 

I noticed this as well. A potential solution might be escaping the comma with a `\,` or replacing the comma with an  `\n`  (that's how Apple calendar does it at least). It seems to be a problem with Apple Calendar. Other clients like Google Calendar, Proton Calendar and Thunderbird do display the address correctly.

> I've added some stuff to the ics list and single templates so all the times and the location/url to the map also end up in the description. Also the doors= and price= are optional, and if there is no doors specified it uses the start= as the door time also. I wasn't sure yet if the start time of the event in the calendar should be the doors-time, or the actual start time, but I guess the actual start time makes sense, and having the doors-time in the description helps to clarify.
> 

Cool. That seems like a clear stylistic choice. I did remove the double mention of the location, though. Would rather have proper display of the address in the location field.

> I think the headers of the meetup markdown files become a bit messy now tho, but I've tried to restructure that a bit with tabs and linebreaks (maybe more personal preference than necessity). Not sure there is anything to do about it so i'm okay with how it is now.
> 

I get it. We could at least use the [summary system](https://gohugo.io/content-management/summaries/) again if we find a way to display the page contents in the 'about' section without showing the summary again (did not find a way to do that, yet).

> One thing I also noticed is that it wasn't possible to run hugo server -F -D, because the [markdown-guide.md](http://markdown-guide.md/) file was an "event" but couldn't be rendered because it does not include the correct info (was an easy fix by just adding the start/end times, but still something we have to look out for in future files that are added as event posts). Finding ways to make this a bit more foolproof would be good maybe.
> 

Should probably add an if start/end time not defined => skip conditional.

> I haven't been able to find where it's coming from, but for some reason the homepage now has a _ in the top left corner.
> 

Found it! Was some standard pseudo-element for the list items that the main theme passed down.



I'll try to push the changes in the upcoming days.

- Richard

**Comment by tmhglnd** [comment]
> * If you go to https://bawdy-waves.surge.sh/events/calendar.ics in your browser: does it give you a valid ics-file at all?

Yes, that works

> * Does subscribing manually via https://bawdy-waves.surge.sh/events/calendar.ics also fail? (http is often more reliable than webcal).

Manually also works :)

> I will try to [check](https://icalendar.org/validator.html?url=http://bawdy-waves.surge.sh/events/calendar.ics) if the ics-template completely adheres to the spec.

Ah useful! That gives some warnings and errors yes that we can look into.

> I noticed this as well. A potential solution might be escaping the comma with a `\,` or replacing the comma with an `\n` (that's how Apple calendar does it at least). It seems to be a problem with Apple Calendar. Other clients like Google Calendar, Proton Calendar and Thunderbird do display the address correctly.

I tried both `\,` and `\n`. The `\,` gives an error `invalid escaped character U+002C ','`. Using `\n` doesn't work either, still just the text up till the `,` that is visible in the address line.

> Cool. That seems like a clear stylistic choice. I did remove the double mention of the location, though. Would rather have proper display of the address in the location field.

Agree, if we get that fixed I don't think the extra location mention is needed.

> I get it. We could at least use the [summary system](https://gohugo.io/content-management/summaries/) again if we find a way to display the page contents in the 'about' section without showing the summary again (did not find a way to do that, yet).

Sure, maybe more a nice-to-have.

> Found it! Was some standard pseudo-element for the list items that the main theme passed down.

Great!

**Comment by tmhglnd** [comment]
Hey, all these changes look good! Nice there was a way to replace `, ` with `\\, ` (also interesting the `\` needs to be escaped also, didn't know!)

I don't see anything that needs extra changing now, you? Shall I merge? :)

**Comment by richardvanthof** [comment]
If the webcall functionality works, sure! If that's still icky I might have to replace that with a way for users to do it via https. Also, thanks for adding me to the community page!

**Comment by tmhglnd** [comment]
It seems all options to subscribe or add events work for me, also the test-link you made in the first post. Not sure what fixed it or why it didn't work for me the first time, but okay. I think I'll merge and then ask the others in the group to try it out, if there are still some issues we can iron those out later based on their feedback :).

>Also, thanks for adding me to the community page!

Sure thing!

**Pull request merged**
